### PR TITLE
Fix Controller loading

### PR DESCRIPTION
**Pull request by fr-esco**
bugfix

### CODE REVIEW

**Comment by fr-esco** [comment]
gulp generator added

**Comment by bsorrentino** [comment]
Well done!

Consider to add a paragraph to README in order to explain, briefly, feature and usage:

**Comment by fr-esco** [comment]
Gulp tasks enhanced.

**Comment by fr-esco** [comment]
Main Gulp tasks are documented directly in CLI.
First version of README has been added.

**Pull request closed without merging**
